name: integration

on: [push, pull_request]

jobs:

  checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        check: [bluecheck, doc8, docs, flake8, isortcheck, mypy, pylint, rstcheck]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install tox
    - name: Run checks with tox
      run: |
        tox -e ${{ matrix.check }}

  tests_x86:
    needs: checks
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }} x64
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - uses: actions/checkout@v2

    - name: Install tox
      run: |
        pip install --upgrade pip
        pip install tox

    - name: Test with tox
      run: tox -e py
      
      
  armv64_job_build_test:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl && \
              python3 -m pip install virtualenv && python3 -m venv py38-venv && \
              source py38-venv/bin/activate && \
                      
              python -m pip install --upgrade pip && \
              python --version && \
              uname -m && \
              whoami && \
              pwd && \
              ls && \
              
              pip install --upgrade pip && \
              pip install tox && \
              tox -e py && \
              
              deactivate'
